experiment:
    save_to: /home/tartandriver/workspace/experiments/yamaha_irl_dino/visual_ablations_50cm_mppi
    name: visual_ablations_sam_pca
    device: cuda
    epochs: 5
    steps_per_epoch: -1
    save_every: 1

footprint:
    params:
        length: 4.0
        width: 2.0
        length_offset: -1.0
        width_offset: 0.0
        nl: 15
        nw: 15

algo:
    type: MPPIIRLSpeedmaps
    params:
        batch_size: 4
        reg_coeff: 1.0e-08
        speed_coeff: 1.0 #turn off speedmaps for now
        grad_clip: 1.0

dataset:
    type: MaxEntIRLDataset
    params:
        root_fp: $TARTANDRIVER_DATA_DIR/big_irl_dataset_postproc/train
        device: cuda
        feature_keys:
            # SAM
            - SAM_0
            - SAM_1
            - SAM_2
            - SAM_3
            - SAM_4
            - SAM_5
            - SAM_6
            - SAM_7
            - SAM_8
            - SAM_9
            - SAM_10
            - SAM_11
            - SAM_12
            - SAM_13
            - SAM_14
            - SAM_15

            # geom
            - terrain
            - terrain_slope
            - diff
            - SVD1
            - SVD2
            - SVD3
            - roughness
            - unknown

network:
    type: ResnetCostmapCategoricalSpeedmapCNNEnsemble2
    params:
        ensemble_dim: 16
        speed_nbins: 15
        max_speed: 15.
        hidden_channels: [128, 128]
        hidden_activation: tanh
#        activation_type: addmin #planner needs nonnegative costs
        activation_type: exponential #planner needs nonnegative costs
        activation_scale: 1.0
        dropout: 0.0

netopt:
    type: Adam
    params: {}

solver:
    type: mpc
    mpc_fp: $TARTANDRIVER_HOME/src/planning/maxent_irl_maps/config/mpc/throttle_mppi.yaml

metrics:
