gascola_test:
  ## need to point to the dir to get the datapoint labels
  classif: /media/airlab/offroad/datasets/2025_irl_kitti/gascola

  metrics:
    bev_bev_inpaint_irl:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251207_runs/baseline_multitask_bev/itr_0004/metricstest_default
    voxel_bev_inpaint_irl:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251207_runs/baseline_multitask/itr_0004/metricstest_default
    voxel_bev_irl_only:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251207_runs/baseline_irl_only/itr_0004/metricstest_default
    bev_bev_irl_only:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251207_runs/baseline_irl_only_bev/itr_0004/metricstest_default
    
    cascaded_semantic_voxels:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251209_baselines/cascaded_semantic_voxels/itr_0004/metricstest_default
    cascaded_vfm_voxels:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251209_baselines/cascaded_vfm_voxels/itr_0004/metricstest_default
    terrainnet_fixed:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251209_baselines/terrainnet_fixed/itr_0004/metricstest_default
    terrainnet_learned:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251209_baselines/terrainnet_learned/itr_0004/metricstest_default
    velociraptor_vfm_bev:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251209_baselines/velociraptor_vfm_bev/itr_0004/metricstest_default
   
renegade_ridge_test:
  classif: /media/airlab/offroad/datasets/2025_irl_kitti/renegade_ridge

  metrics:
    bev_bev_inpaint_irl:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251207_runs/baseline_multitask_bev/itr_0004/metricstest_rr
    voxel_bev_inpaint_irl:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251207_runs/baseline_multitask/itr_0004/metricstest_rr
    voxel_bev_irl_only:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251207_runs/baseline_irl_only/itr_0004/metricstest_rr
    bev_bev_irl_only:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251207_runs/baseline_irl_only_bev/itr_0004/metricstest_rr

    cascaded_semantic_voxels:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251209_baselines/cascaded_semantic_voxels/itr_0004/metricstest_rr
    cascaded_vfm_voxels:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251209_baselines/cascaded_vfm_voxels/itr_0004/metricstest_rr
    terrainnet_fixed:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251209_baselines/terrainnet_fixed/itr_0004/metricstest_rr
    terrainnet_learned:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251209_baselines/terrainnet_learned/itr_0004/metricstest_rr
    velociraptor_vfm_bev:
      /home/tartandriver/workspace/cotrain_irl_experiments/20251209_baselines/velociraptor_vfm_bev/itr_0004/metricstest_rr
  