bev_bev_inpaint_irl:
  /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/baseline_multitask_bev/itr_0004/metricstest_default
voxel_bev_inpaint_irl:
  /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/baseline_multitask2/itr_0004/metricstest_default
voxel_bev_irl_only:
  /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/baseline_irl_only/itr_0004/metricstest_default
bev_bev_irl_only:
  /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/baseline_irl_only_bev/itr_0004/metricstest_default

bev_bev_inpaint_irl_rr:
  /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/baseline_multitask_bev/itr_0004/metricstest_rr
voxel_bev_inpaint_irl_rr:
  /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/baseline_multitask2/itr_0004/metricstest_rr
voxel_bev_irl_only_rr:
  /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/baseline_irl_only/itr_0004/metricstest_rr
bev_bev_irl_only_rr:
  /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/baseline_irl_only_bev/itr_0004/metricstest_rr