gascola_test:
  ## need to point to the dir to get the datapoint labels
  classif: /media/airlab/offroad/datasets/2025_irl_kitti/gascola

  metrics:
    bev_bev_inpaint_irl:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_multitask_bev/itr_0004/metricstest_default
    voxel_bev_inpaint_irl:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_multitask/itr_0004/metricstest_default
    voxel_bev_irl_only:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_irl_only/itr_0004/metricstest_default
    bev_bev_irl_only:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_irl_only_bev/itr_0004/metricstest_default
    bev_bev_inpaint_irl_better_mppi:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_multitask_bev_better_mppi/itr_0004/metricstest_default
    voxel_bev_inpaint_irl_better_mppi:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_multitask_better_mppi/itr_0004/metricstest_default
    
renegade_ridge_test:
  classif: /media/airlab/offroad/datasets/2025_irl_kitti/renegade_ridge

  metrics:
    bev_bev_inpaint_irl_rr:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_multitask_bev/itr_0004/metricstest_rr
    voxel_bev_inpaint_irl_rr:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_multitask/itr_0004/metricstest_rr
    voxel_bev_irl_only_rr:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_irl_only/itr_0004/metricstest_rr
    bev_bev_irl_only_rr:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_irl_only_bev/itr_0004/metricstest_rr
    bev_bev_inpaint_irl_better_mppi:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_multitask_bev_better_mppi/itr_0004/metricstest_rr
    voxel_bev_inpaint_irl_better_mppi:
      /home/tartandriver/workspace/experiments/yamaha_cotrain/real_ablations/distance_based_mppi/baseline_multitask_better_mppi/itr_0004/metricstest_rr
    