experiment:
    save_to: /home/tartandriver/workspace/experiments/yamaha_irl_dino/
    name: irl_radiov3_siglip2_lss
    device: cuda
    epochs: 5
    steps_per_epoch: -1
    save_every: 1

footprint: !include /home/tartandriver/tartandriver_ws/src/planning/maxent_irl_maps/config/footprint/yamaha.yaml

algo: !include /home/tartandriver/tartandriver_ws/src/planning/maxent_irl_maps/config/trainers/mppi_irl_speedmaps.yaml

dataset: !include /home/tartandriver/tartandriver_ws/src/planning/maxent_irl_maps/config/dataset/bev_irl_train.yaml

network: !include /home/tartandriver/tartandriver_ws/src/planning/maxent_irl_maps/config/networks/bev_lss.yaml

netopt:
    type: Adam
    params: {}

solver:
    type: mpc
    mpc_fp: /home/tartandriver/tartandriver_ws/src/planning/maxent_irl_maps/config/mpc/kbm_mppi.yaml